### PR TITLE
Add keplr to `InjectedConnector`

### PR DESCRIPTION
**Pull request by Thunnini**
### Issue / feature description

keplr now supports starknet. Therefore, I would like starknetkit to support keplr.

### Changes

- Add keplr to `defaultConnectors`
- Add keplr logo

### Checklist

- [ ] Rebased to the last commit of the target branch (or merged)
- [ ] Code self-reviewed
- [ ] Code self-tested
- [ ] Tests updated (if needed)
- [ ] All tests are passing locally

Please keep your pull request as small as possible. If you need to make multiple changes, please create separate pull requests for each change. Create a draft pull request if you need early feedback. This will mark the pull request as a work in progress and prevent it from being reviewed or merged until you are ready.

Please move drafts to the ready for review (regular PR) when you are ready to start the review process and other developers will pick it up from there.

### CODE REVIEW

**Comment by bluecco** [comment]
Did some tests and leaving some comments:
- this pr won't be merged at this moment, because it will change the default connectors list
- keplr can be already used by initializing the injected connector
  - `new InjectedConnector({ options: { id: "keplr" } })`
- using starknetkit `connect` method, it needs to be passed to the `connectors` option
```typescript 
const res = await connect({
      connectors: [
        new InjectedConnector({ options: { id: "argentX" } }),
        new InjectedConnector({ options: { id: "braavos" } }),
        new InjectedConnector({ options: { id: "keplr" } }),
        new ArgentMobileBaseConnector({
          dappName: "Starknetkit example dapp",
          url: window.location.hostname,
          chainId: CHAIN_ID,
          icons: [],
        }),
        new WebWalletConnector({ url: ARGENT_WEBWALLET_URL }),
      ],
      modalMode: "alwaysAsk",
    })

    const { wallet, connectorData, connector } = res
```

- discovery is not working for keplr at the moment, we need to wait for `@starknet-io/get-starknet-core` to be updated for this

**Comment by Thunnini** [comment]
@bluecco Then, can you leave out the default connectors list part and just add the icon part?

**Comment by bluecco** [comment]
@Thunnini yes, adding in #142
will do some tests on the pre-release first

**Comment by bluecco** [comment]
closing this in favour of #142 
new starknetkit@latest can be used (v2.3.3)

- can connect with keplr
- can send a transaction if the account is `deployed`

there are 2 issues on wallet side:
- cannot sign a message
- cannot perform a transaction if the account is `undeployed`

**Pull request closed without merging**
